### ISSUE TITLE
Not constraining item inside of grid

### ISSUE THREAD

**Issue by slauzinho** [ge6285790/react-native-sortable-gridview#1]
Is there a way of not constraining the item to be inside the grid when selected.
I have a `<View>` above and below the item and I'm trying to implement some sort of drop zone, but when the item is selected it seems that the zIndex is set to a negative number because it's under all other views

**Comment by ge6285790** [comment]
Hi @slauzinho , thanks for giving this project a try, would you mind providing some sample code to demonstrate the issue ?

**Comment by ge6285790** [comment]
Hi @slauzinho , you can update the react-native-sortable-gridview to the 1.1.0 version.
I add three props and adjust the style in this version, hope it could help you.

There are two solutions can let the item won't be constraining.

1. Adjust SortableGridview style.
```javascript
<SortableGridview
  style={{overflow: 'visiable'}} // => you can use hidden / visiable / scroll
  ...
/>
```

2. Use new props for custom header, footer and make SortableGridview scrollable.
```javascript
<SortableGridview
  style={{overflow: 'scroll'}}
  useScrollView={true}
  headerComponent={() => {
    return <Text style={styles.title}>Default</Text>
  }}
  footerComponent={() => {
    return <Text style={styles.title}>footer</Text>
  }}
  ...
/>
```

Hope this answer can help you :D.
If there are any problems, please feel free to let me know.
Thanks!

**Comment by slauzinho** [comment]
Hey, thank you for your great work.

The fix you implemented solved my issue!! Thank you so much :)
