### ISSUE TITLE
Responsive: Tablet's and Ipad's

### ISSUE THREAD

**Issue by rodrigowpl** [ge6285790/react-native-sortable-gridview#2]
First for all, great library, this is helping me a lot!

Quick questions: What would your approach to handling with different screen sizes? For ex: Tablet's and Ipad's in your grid system?

For example, see my print screen attached:
<img width="526" alt="Screen Shot 2019-09-03 at 18 44 28" src="https://user-images.githubusercontent.com/18172307/64210912-e849e680-ce7a-11e9-8f99-9537b31ee1af.png">

Here I'm setting up 3 columns each row by the prop `numPerRow`, how could I set up in a responsive way?

Thanks,

**Comment by ge6285790** [comment]
Hi @rodrigowpl , thanks for giving this project a try!
I'm not sure if my implementation work for you, but maybe you could give it a try.

```
renderItem = {(item, index) => {
  return (
    <View
      uniqueKey={item.name} // Important! Should add this props!!!
      style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center'}}  // => let your item fit to the subcontainer below the SortableGridview which width is equal to (SortableGridview's width / numPerRow)
    >
      <Image style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0}} resizeMode="cover" source={...} /> // => let your image fit to your Item container.
    </View>
  )
}}

render() {
  return (
    <SortableGridview
      style={{width: screenWidth}} // => you can set any width that you want.
      numPerRow={3} // => this props will slice container to 3 piece, in this case, each piece's width will be screenWidth / 3.
      ...
      renderItem={this._renderItem}
    />
  )
}
```

Hope this will help you! thanks.

**Comment by rodrigowpl** [comment]
Thanks for your answer!

Coincidentally we did the same solution and it works perfectly :D

You can close the issue
