### ISSUE TITLE
GridView inside a scrollview

### ISSUE THREAD

**Issue by surajit-das-bitcanny** [ge6285790/react-native-sortable-gridview#4]
When we use GridView inside a scrollview and we try to re-arrange by dragging the item, the scrollview also get scrolled with it which makes it very annoying. Using it inside normal View works well but in a ScrollView we should fix the scroll when the item is dragged.

Expected behaviour: The scrollview should stay fixed when the item dragged and re-arranged.

**Comment by ge6285790** [comment]
Hi surajit-das-bitcanny,
There's a easy way to resolve your question.

```javascript
class Example extends React.Component {
  state = {
    scrollEnabled: true, // default set ScrollView enable scroll
  }
  render() {
    return (
      <ScrollView
        scrollEnabled={this.state.scrollEnabled} // set enable/disable scroll
      >
        <SortableGridview
          ...
          onDragStart={() => {
            this.setState({
              scrollEnabled: false, // disable scroll
            })
          }}
          onDragRelease={() => {
            this.setState({
              scrollEnabled: true, // enable scroll
            })
          }}
          ...
       />
    );
  }
}
```

**Comment by surajit-das-bitcanny** [comment]
Thanks for the reply! It works.
